services:
  frontend:
    build: ./client
    image: gideon1828/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: gideon1828/backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
